/*
 * Provides the various states the screen can be in.
 */

#ifndef SCREENS_H
#define SCREENS_H

enum Screen {
    SCREEN_MENU,
    SCREEN_PAUSE,
    SCREEN_ENDLESS,
    SCREEN_HIGHSCORE,
    SCREEN_DIED,

    SCREEN_STORY_1A1,
    SCREEN_STORY_1A2,
    SCREEN_STORY_1S3,
    SCREEN_STORY_1P3,
    SCREEN_STORY_1A4,
    SCREEN_STORY_1R5,
    SCREEN_STORY_1E5,
    SCREEN_STORY_BATTLE_1,

    SCREEN_STORY_2A1,
    SCREEN_STORY_2A2,
    SCREEN_STORY_2A3,
    SCREEN_STORY_2B4,
    SCREEN_STORY_2A5,
    SCREEN_STORY_2A6,
    SCREEN_STORY_2E7,
    SCREEN_STORY_2A7,
    SCREEN_STORY_BATTLE_2,

    SCREEN_STORY_3A1,
    SCREEN_STORY_3B2,
    SCREEN_STORY_3A3,
    SCREEN_STORY_3A4,
    SCREEN_STORY_3A5,
    SCREEN_STORY_3A6,
    SCREEN_STORY_3A7,
    SCREEN_STORY_3A8,
    SCREEN_STORY_TORTURE,

    SCREEN_STORY_4A1,
    SCREEN_STORY_4A2,
    SCREEN_STORY_4A3,
    SCREEN_STORY_4A4,
    SCREEN_STORY_4B5,
    SCREEN_STORY_4A6,
    SCREEN_STORY_4A7,
    SCREEN_STORY_4B7,
    SCREEN_STORY_4A8,
    SCREEN_STORY_BATTLE_4,

    SCREEN_STORY_5A1,
    SCREEN_STORY_5A2,
    SCREEN_STORY_5A3,
    SCREEN_STORY_5B4,
    SCREEN_STORY_5A5,
    SCREEN_STORY_5A6,
    SCREEN_STORY_5B6,
    SCREEN_STORY_BATTLE_5,

    SCREEN_STORY_6A1,
    SCREEN_STORY_6A2,
    SCREEN_STORY_6A3,
    SCREEN_STORY_6B3,
    SCREEN_STORY_BATTLE_6,

    SCREEN_STORY_7W1,
    SCREEN_STORY_7L1,
    SCREEN_STORY_7A2,
    SCREEN_STORY_7B2,

    SCREEN_UNLOCKS,
    SCREEN_OPTIONS,
    SCREEN_DELETE_CHECK_ONE,
    SCREEN_DELETE_CHECK_TWO
};

#endif /* SCREENS_H */
